package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.ExecBuildStep
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.exec
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Up'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Up")) {
    params {
        add {
            text("env.ASPNETCORE_ENVIRONMENT", "Production", allowEmpty = false)
        }
        add {
            password("env.BOT_TOKEN", "credentialsJSON:2621532b-400f-4938-886a-415e4adad6e5", display = ParameterDisplay.HIDDEN)
        }
        add {
            password("env.POSTGRES_PASSWORD", "credentialsJSON:5855d4d5-c1de-4d3d-849f-8ba2b77beffd", display = ParameterDisplay.HIDDEN, readOnly = true)
        }
    }

    expectSteps {
        exec {
            path = "build.sh"
            arguments = "Up --skip"
        }
    }
    steps {
        insert(0) {
            step {
                name = "Production docker-compose configuration"
                type = "MRPP_CreateTextFile2"
                param("system.dest.file", "%teamcity.build.checkoutDir%/src/docker-compose.override.yml")
                param("content", """
                    version: '3.7'
                    
                    services:
                      ppbot:
                        environment:
                          - ASPNETCORE_ENVIRONMENT=%env.ASPNETCORE_ENVIRONMENT%
                        networks:
                          - pp_bot_network
                    
                    networks:
                      pp_bot_network:
                        external:
                          name: postgres_network
                """.trimIndent())
            }
        }
        insert(1) {
            step {
                name = "Production database settings"
                type = "MRPP_CreateTextFile2"
                param("system.dest.file", "%teamcity.build.checkoutDir%/src/pp_bot.Server/dbsettings.Production.json")
                param("content", """
                    {
                        "ConnectionStrings": {
                            "DB_CONN_STR": "Host=postgres;Port=5432;UserId=pp_bot;Password=%env.POSTGRES_PASSWORD%;Database=pp_bot;CommandTimeout=300;"
                        }
                    }
                """.trimIndent())
            }
        }
        insert(2) {
            step {
                name = "Production bot settings"
                type = "MRPP_CreateTextFile2"
                param("system.dest.file", "%teamcity.build.checkoutDir%/src/pp_bot.Server/botsettings.Production.json")
                param("content", """
                    {
                        "BOT_TOKEN": "%env.BOT_TOKEN%"
                    }
                """.trimIndent())
            }
        }
        update<ExecBuildStep>(3) {
            clearConditions()
        }
    }
}
