package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.exec
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Up'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Up")) {
    expectSteps {
        exec {
            path = "build.sh"
            arguments = "Up --skip"
        }
    }
    steps {
        insert(1) {
            step {
                name = "Production docker-compose configuration"
                type = "MRPP_CreateTextFile2"
                param("system.dest.file", "%teamcity.build.checkoutDir%/src/docker-compose.override.yml")
                param("content", """
                    version: '3.7'
                    
                    services:
                      ppbot:
                        environment:
                          - ASPNETCORE_ENVIRONMENT=%env.ASPNETCORE_ENVIRONMENT%
                      postgres:
                        environment:
                          - POSTGRES_PASSWORD=%env.POSTGRES_PASSWORD%
                """.trimIndent())
            }
        }
    }
}
