version: '3.9'

x-restart-policy: &restart_policy
  restart: unless-stopped

x-host-config: &host_config
  environment:
    - ASPNETCORE_ENVIRONMENT=Development

services:
  ppbot:
    <<: *restart_policy
    <<: *host_config
    container_name: pp_bot_app
    image: ppbot/host:latest
    build:
      context: .
      dockerfile: pp_bot.Server/Dockerfile